### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by addorman** [jpush/jmessage-api-php-client#1]
1、IM文件夹中一些类的方法名命名为 list 与php内部函数冲突。
2、IM\Message.php 里面 $options 数组中应用逗号。

**Comment by ghost** [comment]
感谢你的反馈，关于第一点 PHP 自己的 list 函数和成员方法是不会冲突的，你可以调用着试一下，而且调用的写法也是不一样的。

第二点确实是我的代码的问题，真亏你能找出来，然后你方便提个 PR 来修改吗

**Comment by ghost** [comment]
fixed in https://github.com/jpush/jmessage-api-php-client/commit/45b05e07ce23dacc9f2df3c0370641ce31c7f09b

**Comment by ghost** [comment]
关于第一点，确实是有毛病的，低版本的 PHP 确实存在这个问题
