### ISSUE TITLE
list() 函数兼容性问题

### ISSUE THREAD

**Issue by chenyuxh** [jpush/jmessage-api-php-client#2]
$user->list($start, $count);

获取用户列表的函数， list作为php的关键词， 不能作为函数名

**Comment by ghost** [comment]
![screenshot_2017-02-13_02-12-41](https://cloud.githubusercontent.com/assets/8064048/22868802/cdcacd42-f191-11e6-8d43-aa0ffb509b36.png)

确实只有 PHP 7.0 以后的版本才是没有问题的，但是在之前的版本中就会有语法错误了，这个是一定要改过去的，所以我现在正在想一个能够替换的函数名，有什么意见吗

**Comment by ghost** [comment]
好了，我全部改成 listAll() 吧

**Comment by chenyuxh** [comment]
赞一个

**Comment by ghost** [comment]
fixed in https://github.com/jpush/jmessage-api-php-client/commit/1175b57459fb8157c18087c7bf6ec7f7b2e34412
已发布一个版本解决： https://github.com/jpush/jmessage-api-php-client/releases/tag/1.0.3
已同步至 packagist： https://packagist.org/packages/jiguang/jmessage#1.0.3
