### ISSUE TITLE
tag 1.1.5

### ISSUE THREAD

**Issue by what-00** [jpush/jmessage-api-php-client#5]
tag 1.1.5
JMessage\IM\User.php
forbidden method API is PUT Request.

JMessage\IM\ChatRoom.php 
showBatch method ...

**Comment by ghost** [comment]
fixed with 1.1.6，update and try

**Comment by what-00** [comment]
JMessage\IM\User.php
forbidden 方法中的$uri拼接地址应该forbidden?disable=, SDK上=符号没有, 在disable=false时 API response 500 错误,但请求是生效的

**Comment by what-00** [comment]
JMessage\IM\ChatRoom.php
memebers method 在SDK文档上是 $room->members($roomId, $count, $start = 0));

**Comment by ghost** [comment]
其实你可以提个pr的 1.1.7
