### ISSUE TITLE
无法更新聊天室的信息

### ISSUE THREAD

**Issue by LiberoFile** [jpush/jmessage-api-php-client#8]
$client = new JMessage($appKey, $masterSecret);
        $jgRoom = new ChatRoom($client);
        $options = array([
            'name' => $data->name,
            'description' => $data->synopsis,
            'owner_username' => $data->admin,
        ]);
        $response = $jgRoom->update($roomId, $options);
报错了{"headers":{"0":"HTTP\/1.1 400 Bad Request","Server":"nginx","Date":"Fri, 27 Apr 2018 10:06:05 GMT","Content-Type":"application\/json;charset=UTF-8","Content-Length":"56","Connection":"keep-alive","X-Rate-Limit-Limit":"600","X-Rate-Limit-Remaining":"597","X-Rate-Limit-Reset":"20"},"body":{"error":{"code":899003,"message":"parameter invalid!"}},"http_code":400} 
$appKey, $masterSecret，$roomId都是正确的，请问是哪里出问题了

**Comment by ghost** [comment]
```
$options = array([
'name' => $data->name,
'description' => $data->synopsis,
'owner_username' => $data->admin,
]);
```

这个的结果是二维数组

**Comment by LiberoFile** [comment]
我写成这样
$options['name'] = roomName
$options['description'] = roomDescription
$options['owner_username'] = ownerUsername
或者写成这样
$options[0] = roomName
$options[1] = roomDescription
$options[2] = ownerUsername
都是报相同的错误
{"code":899003,"message":"parameter invalid!"}

**Comment by ghost** [comment]
```php
<?php
require __DIR__ . '/config.php';
use JMessage\IM\ChatRoom;

$room = new ChatRoom($jm);

// $response = $room->create('root01', 'user_0');
// print_r($response);

$response = $room->show('10037216');
print_r($response);

$response = $room->update('10037216', [
    "owner_username" => "user_0",
    "name"  =>  "root01",
    "description" => "pp"
]);
print_r($response);
```

你‘按照上面的 example 自己运行下试试
